--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DuoIncure/ComplexUpgradeUI
build-by-default: true
branches:
- pm4
projects:
  ComplexUpgradeUI:
    path: ""
    icon: "resources/image/book.gif"
    libs:
      - src: BreathTakinglyBinary/libDynamicForms/libDynamicForms
        version: ^1.2.0
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.1
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
    lint:
      phpstan: false
...
