--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DuoIncure/ComplexUpgradeUI
build-by-default: true
branches:
- master
projects:
  ComplexUpgradeUI:
    path: ""
    libs
      - src: BreathTakinglyBinary/libDynamicForms/libDynamicForms
        version: ^1.1.2
    lint:
      phpstan: false
...
