---
name: ComplexUpgradeUI
version: 2.0.0
main: DuoIncure\ComplexUpgradeUI\UpgradeMain
api: 4.0.0
src-namespace-prefix: DuoIncure\ComplexUpgradeUI
description: Upgrade your tools in a UI using XP!
permissions:
  upgradeui.command.upgrade:
    default: true
    description: Open the Upgrade UI
...