---
#Title of form. Use & for colours
form-title: "&l&6UpgradeUI"

# Economy Options
economy:
  # Economy provider to use. Supported options:  "economyapi", "bedrockeconomy" and "xp"
  provider: xp
  # Cost per enchant level. If money is chosen 1 = $1. If XP is chosen 1 = 1 XP level.
  cost: 5

#List of enchants and their configurable values
#PLEASE NOTE. SOME ENCHANTS ARE NOT ADDED BY POCKETMINE-MP AND AS A RESULT ARE NOT IN THIS PLUGIN.
enchants:
  #The tool for the enchants
  pickaxe:
    #Enchant name
    efficiency:
      #Max level for enchant
      max-level: 5
    #Enchant name
    unbreaking:
      #Max level for enchant
      max-level: 3
    #Enchant name
    silk_touch:
      #Max level for enchant
      max-level: 1
  shovel:
    efficiency:
      max-level: 5
    unbreaking:
      max-level: 3
    silk_touch:
      max-level: 1
  axe:
    efficiency:
      max-level: 5
    unbreaking:
      max-level: 3
    sharpness:
      max-level: 5
  sword:
    sharpness:
      max-level: 5
    knockback:
      max-level: 2
    fire_aspect:
      max-level: 2
  bow:
    power:
      max-level: 5
    punch:
      max-level: 2
    flame:
      max-level: 2
    infinity:
      max-level: 1
  helmet:
    protection:
      max-level: 4
    fire_protection:
      max-level: 4
    blast_protection:
      max-level: 4
    projectile_protection:
      max-level: 4
    thorns:
      max-level: 3
    respiration:
      max-level: 3
  chestplate:
    protection:
      max-level: 4
    fire_protection:
      max-level: 4
    blast_protection:
      max-level: 4
    projectile_protection:
      max-level: 4
    thorns:
      max-level: 3
  leggings:
    protection:
      max-level: 4
    fire_protection:
      max-level: 4
    blast_protection:
      max-level: 4
    projectile_protection:
      max-level: 4
    thorns:
      max-level: 3
  boots:
    protection:
      max-level: 4
    fire_protection:
      max-level: 4
    blast_protection:
      max-level: 4
    projectile_protection:
      max-level: 4
    thorns:
      max-level: 3
    feather_falling:
      max-level: 4
...